
/// THIS FILE WAS AUTOGENERATED WITH validateEnv.
/// <reference types="vite/client" />
/// <reference types="vite-plugin-svgr/client" />

interface ImportMetaEnv {
    VITE_BACKEND_BASE_URL: string;
}
    